{
 "title": "greye",
 "description": "https://github.com/ftrigari/greye/tree/main",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(application_under_monitoring,namespace)"
    }
   },
   {
    "name": "monitoringPod",
    "query": {
     "query": "label_values(application_under_monitoring,service)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(application_under_monitoring{service=~\"$monitoringPod\"},name)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Application monitored",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 1, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(application_under_monitoring)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Application request",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(application_counter{namespace=~\"$namespace\", service=~\"$monitoringPod\", name=~\"$service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application in alarms",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(application_in_alarm{namespace=~\"$namespace\", service=~\"$monitoringPod\", name=~\"$service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application in allarms",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 1, "y": 9 },
   "targets": [
    {
     "expr": "application_in_alarm{namespace=~\"$namespace\", service=~\"$monitoringPod\", name=~\"$service\"} > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application monitored",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 9, "y": 9 },
   "targets": [
    {
     "expr": "application_under_monitoring{namespace=~\"$namespace\", service=~\"$monitoringPod\", name=~\"$service\"} > 0",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Application executed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 1, "y": 17 },
   "targets": [
    {
     "expr": "application_counter{namespace=~\"$namespace\", service=~\"$monitoringPod\", name=~\"$service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "application_latency{namespace=~\"$namespace\", service=~\"$monitoringPod\", name=~\"$service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Cluster monitored",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 1, "y": 27 },
   "targets": [
    { "expr": "cluster_under_monitoring{} > 0", "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "Cluster not discovered",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 27 },
   "targets": [
    {
     "expr": "cluster_under_monitoring{} == 0",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Cluster in error",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 15, "y": 27 },
   "targets": [
    { "expr": "cluster_in_alarm {} > 0", "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "Request executed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 1, "y": 35 },
   "targets": [
    { "expr": "cluster_counter{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Cluster request",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 15, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(cluster_counter{})", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cluster in alarm",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 1, "y": 43 },
   "targets": [
    { "expr": "cluster_in_alarm", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 15, "y": 43 },
   "targets": [
    { "expr": "cluster_latency{}", "legendFormat": "__auto" }
   ]
  },
  { "title": "Go metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "go_routine",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 1, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_goroutines{container=\"greye\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory heap used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 10, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{container=\"greye\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "memory heap already reserved",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_sys_bytes{container=\"greye\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 1, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container=\"greye\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 68 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"greye\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}